from ..classes.option import Option
from ..classes.menumanager import manager

manager.create_menu(app_name="Miro",
                    menu_name="Main",
                    options=[
                            Option(label = "Print App Name", 
                                   function = manager.f_printAppName()), 
                            Option(label = "Navigation",
                                   function = manager.switch_to(app_name="Miro",menu_name="Navigation"),
                                   on_dwell=True,
                                   bg_color="ddaa00bb"),
                            Option(label = "Active Windows",
                                   function = manager.f_key("win-tab")), 
                            Option(label = "Last Window",
                                   function = manager.f_key("alt-tab"),),
                     ]
                     )

manager.create_menu(app_name="Miro",
                    menu_name="Navigation",
                    options=[
                            Option(label = "Pan Right",
                                   function = manager.f_key_press_hold("right"),
                                   bg_color="ff3f3fbb",
                                   on_hover=True),
                            Option(label = "Fit Selected",
                                   function = manager.f_key("alt-2"),
                                   bg_color="ff3f3fbb",),
                            Option(label = "Pan Up",
                                   function = manager.f_key_press_hold("up"),
                                   bg_color="ff3f3fbb",
                                   on_hover=True),
                            Option(label = "Zoom In",
                                   function = manager.f_key("ctrl-="),
                                   bg_color="ff3f3fbb",
                                   on_hover=True,
                                   hover_delay=0.5,),
                            Option(label = "Pan Left",
                                   function = manager.f_key_press_hold("left"),
                                   bg_color="ff3f3fbb",
                                   on_hover=True),
                            Option(label = "Zoom Out",
                                   function = manager.f_key("ctrl--"),
                                   bg_color="ff3f3fbb",
                                   on_hover=True,
                                   hover_delay=0.5,),
                            Option(label = "Pan Down",
                                   function = manager.f_key_press_hold("down"),
                                   bg_color="1f1fffbb",
                                   on_hover=True),
                            Option(label = "Fit All",
                                   function = manager.f_key("alt-1"),
                                   bg_color="ff3f3fbb",),
                     ]
                     )